version: "3"
services:
  bookingsg:
    build:
      context: ./
      dockerfile: ./service.node12.watch.dockerfile
    container_name: "bookingsg"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    ports:
      - 3999:3000
      - 6999:6000
    volumes:
      - ./src:/service/src:delegated
      - ./package.json:/service/package.json:delegated
      - ./package-lock.json:/service/package-lock.json:delegated
      - ./params:/service/params:delegated
      - bookingsg-dist:/service/dist
    depends_on:
      - db
  db:
    image: "postgres:12"
    container_name: "gt_postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: D8L6xJspQbvaUwukQLqd
      POSTGRES_DB: govtech
      POSTGRES_USER: gtbooking
    volumes:
      - gt_dbdata:/var/lib/postgresql/data
volumes:
  gt_dbdata:
  bookingsg-dist:
