version: "3"
services:
  bookingsg-api:
    build:
      context: ./
      dockerfile: ./node_modules/mol-lib-config/shared-config/service.node12.watch.dockerfile
    container_name: "bookingsg-api"
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    ports:
      - 3999:3000
      - 6999:6000
    volumes:
      - ./src:/service/src:delegated
      - ./package.json:/service/package.json:delegated
      - ./package-lock.json:/service/package-lock.json:delegated
      - ./.env:/service/.env:delegated
      - bookingsg-api-dist:/service/dist
      - bookingsg-api-node_modules:/service/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: gt_postgres
      DB_PORT: 5432
      DB_DATABASE: govtech
      DB_USERNAME: "gtbooking"
      DB_PASSWORD: "D8L6xJspQbvaUwukQLqd"
  db:
    image: "postgres:11"
    container_name: "gt_postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: D8L6xJspQbvaUwukQLqd
      POSTGRES_DB: govtech
      POSTGRES_USER: gtbooking
    volumes:
      - gt_dbdata:/var/lib/postgresql/data
volumes:
  gt_dbdata:
  bookingsg-api-dist:
  bookingsg-api-node_modules:
