version: "3"
services:
  db:
    image: "postgres:12"
    container_name: "gt_postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: D8L6xJspQbvaUwukQLqd
      POSTGRES_DB: govtech
      POSTGRES_USER: gtbooking
    volumes:
      - gt_dbdata:/var/lib/postgresql/data
  bookingsg:
    build:
      context: ./
      dockerfile: ./service.node12.watch.dockerfile
    container_name: "bookingsg"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    ports:
      - 3999:3000
      - 6999:6000
    volumes:
      - ./src:/service/src:delegated
      - ./package.json:/service/package.json:delegated
      - ./package-lock.json:/service/package-lock.json:delegated
      - bookingsg-dist:/service/dist
      - ./.env:/service/.env:delegated
    depends_on:
      - db
      - appointment-mq-node-1
      - appointment-mq-node-2
  appointment-mq-node-1:
    image: rmohr/activemq:5.15.9
    container_name: appointment-mq-node-1
    hostname: activemq-node-1
    ports:
      - "61616:61616"
      - "8161:8161"
  appointment-mq-node-2:
    image: rmohr/activemq:5.15.9
    container_name: appointment-mq-node-2
    hostname: activemq-node-2
    ports:
      - "61617:61616"
      - "8162:8161"
volumes:
  gt_dbdata:
  bookingsg-dist:
