// STUB
import './components/bookingChangeLogs/bookingChangeLogs.controller';
import './components/bookings/bookings.controller';
import './components/scheduleForms/scheduleForms.controller';
import './infrastructure/infrastructure.controller';
import './components/timeslots/timeslots.controller';
import './components/organisations/organisations.controller';
import './components/services/services.controller';
import './components/serviceProviders/serviceProviders.controller';
import './components/users/users.controller';
import './components/captcha/usersessions.controller';
import './components/unavailabilities/unavailabilities.controller';
